### ISSUE TITLE
You are calling a deprecated version of the Ads API. Please update to the latest version: v2.10.

### ISSUE THREAD

**Issue by sidharth28** [singer-io/tap-facebook#11]
****Facebook TaP NOt working...****

Config File :
{"start_date":"2016-02-02",
"account_id":"104104556902392",
"access_token":"EAAKPKW4rDdEBAIv4VK6aoiCjAtWDZBGN46W0ZAjQYNjsTQ9L8aRGsfsVbZBgOyjqzhFjs3ktavpvoKQiSKbAZAtQoborQZCnVuxFCzcZCea30x3oq94Dy8fI8x1gEbFAK2dRo6mlZAHJe7dtgY4a580LOILZAM4BhoNFbVZCNXNZBu6OcP2tV9OH1dHnMGGDfwsVbm9I8IwZBwn9nVwZCS6BkOYsE76BgGsehkcZD"}

Properties File :

[{ "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": null,
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "age_and_gender",
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
"properties.json" 44L, 1859C
[{ "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": null,
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "age_and_gender",
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
[{ "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": null,
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "age_and_gender",
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
[{ "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": null,
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "age_and_gender",
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
[{ "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": null,
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "age_and_gender",
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
[{ "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": null,
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "age_and_gender",
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
[{ "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": null,
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "age_and_gender",
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
[{ "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": null,
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "age_and_gender",
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
[{ "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": null,
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "age_and_gender",
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "country",
[{ "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": null,
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "age_and_gender",
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "country",
   "action_attribution_windows": ["1d_click",
[{ "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": null,
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "age_and_gender",
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "country",
   "action_attribution_windows": ["1d_click",
   "breakdowns": null,
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "age_and_gender",
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",
                                  "28d_view"] },
 { "level" : "ad",
   "actions_breakdowns": ["action_type",
                          "action_target_id",
                          "action_destination"],
   "breakdowns": "country",
   "action_attribution_windows": ["1d_click",
                                  "7d_click",
                                  "28d_click",
                                  "1d_view",
                                  "7d_view",

Error:

  Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v2.8/me/adaccounts
  Params:  {'summary': 'true'}

  Status:  400
  Response:
    {
      "error": {
        "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.10.",
        "type": "OAuthException",
        "code": 2635,
        "fbtrace_id": "HyzA5DGRz3Q"
      }
    }

**Comment by briansloane** [comment]
The master branch of the Facebook tap is now using v2.10
