### ISSUE TITLE
update to API v9

### ISSUE THREAD

**Issue by sherifnada** [singer-io/tap-facebook#114]
Hi there, 

[Facebook released v9 of their API on November 10](https://developers.facebook.com/docs/graph-api/changelog/). This means that new Facebook apps cannot use this connector unless it is updated to v9. The tap fails with an error like the following: 

```
  Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v8.0/me/adaccounts
  Params:  {'summary': 'true'}

  Status:  400
  Response:
    {
      "error": {
        "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v9.0.",
        "type": "OAuthException",
        "code": 2635,
        "fbtrace_id": "APOaj0bkymwIFMmFAWNb-W3"
      }
    }

CRITICAL
CRITICAL
CRITICAL   Message: Call was not successful
CRITICAL   Method:  GET
CRITICAL   Path:    https://graph.facebook.com/v8.0/me/adaccounts
CRITICAL   Params:  {'summary': 'true'}
CRITICAL
CRITICAL   Status:  400
CRITICAL   Response:
CRITICAL     {
CRITICAL       "error": {
CRITICAL         "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v9.0.",
CRITICAL         "type": "OAuthException",
CRITICAL         "code": 2635,
CRITICAL         "fbtrace_id": "APOaj0bkymwIFMmFAWNb-W3"
CRITICAL       }
CRITICAL     }
```

is updating to v9 on the roadmap for this tap?

**Comment by sherifnada** [comment]
@luandy64 I'm happy to submit a PR if you have bandwidth to review

**Comment by luandy64** [comment]
@sherifnada I can get your PR reviewed if you can make the change and test it

**Comment by luandy64** [comment]
Skimming the changelog, it doesn't look like any of the endpoints used by the tap are changing, can you confirm that?

**Comment by sherifnada** [comment]
@luandy64 full transparency: I won't be able to get this for some time. In the best case it's a small change and doesn't take much time but in case more hands-on work is needed I don't have the bandwidth at the moment. I'll check back in a few weeks.

**Comment by Thor1** [comment]
Has any one got this working with the Facebook API v9.

**Comment by datageek** [comment]
> Has any one got this working with the Facebook API v9.

I've gotten it to work for my needs, which may not be the same as yours so I wouldn't say everything works. If you go into the `facebook-business` package tap-`facebook` utilizes and change the `api_version` from `8.0` to `9.0` it will at least start to pull data.  you can find it in the `apiconfig.py` file.

**Comment by briansloane** [comment]
This was resolved in https://github.com/singer-io/tap-facebook/pull/133
