### ISSUE TITLE
Upgrade to Facebook API v3.3

### ISSUE THREAD

**Issue by cmerrick** [singer-io/tap-facebook#58]
Changelog: https://developers.facebook.com/docs/graph-api/changelog/version3.3#marketing-api

We do not expect any breaking changes based on the changelog.

Steps:
1 . Update the Facebook SDK version to `3.3` in `setup.py`
2. Run tap-tester tests

**Comment by aiguofer** [comment]
Taking a look at the changelog, the one thing that jumped out at me was `Deprecated several Insights API metrics, including action_type breakdowns`. 

Without digging much into the FB API, I see a few references to action_type [breakdowns in the code](https://github.com/singer-io/tap-facebook/blob/master/tap_facebook/__init__.py#L511). I'm guessing the only breakdowns the tap uses are these, in which case the deprecations shouldn't affect the tap. Is that right?

**Comment by cmerrick** [comment]
The changelog entry is confusing. We believe this part:

> The following action types are entirely deprecated from all Insights API metrics:
> offline_conversion
> onsite_conversion.messaging_reply — You can replace with a custom formula as onsite_conversion.messaging_first_reply divided by onsite_conversion.messaging_conversation_started
> receive_offer — Replacement action type is onsite_conversion.post_save
> commerce_event
> commerce_event.add_to_cart
> commerce_event.purchase
> commerce_event.message_to_buy
> commerce_event.other
> commerce_event.view_content 

means that these specific values of the `action_type` dimension won't be returned when the `action_type` breakdown is requested. This is confirmed by the docs, which say that:

> The following are the possible breakdowns that can be supplied into the action_breakdowns field.
> action_converted_product_id
> action_device
> action_canvas_component_name
> action_carousel_card_id
> action_carousel_card_name
> action_destination
> action_reaction
> action_target_id
> action_type
> action_video_sound
> action_video_type

**Comment by aiguofer** [comment]
Great, yeah that's what I figured. Seems like an easy enough change :)

**Comment by cmerrick** [comment]
Fixed by #59
