### ISSUE TITLE
IMPORTANT: Facebook Marketing API v4 sunset

### ISSUE THREAD

**Issue by Jude188** [singer-io/tap-facebook#86]
I've noticed that the current version of `tap-facebook` seems to be using version 4.0.2 of the Facebook Marketing API. This API is being sunset on 31st March 2020.

The next version (v5) is also being sunset at the end of May 2020.

Because of this it surely makes sense to skip v5 and move straight to v6? This will, obviously, need to be done before the end of March.

https://developers.facebook.com/docs/graph-api/changelog#marketing-api-changelog

**Comment by luandy64** [comment]
@Jude188 I have a WIP branch with a bump to V6 in #88 

If you are have data with `relevance_score` or `video_10_sec_watched_actions`, I would love more testers running the branch and verifying the tap still works.
