### ISSUE TITLE
"Unsupported get request. Object with ID 'act_XXXXX' does not exist,..."

### ISSUE THREAD

**Issue by mattredlon** [singer-io/tap-facebook#93]
Getting this error across multiple Stitch connectors for the last several days. Not sure what to do to resolve. I have reauthorized account and confirmed permissions are still set appropriately. Any suggestions appreciated!

`Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v6.0/act_4XXXXXXXXXXXX4/ads
  Params:  {'limit': 100, 'filtering': '[{"field":"ad.delivery_info","operator":"IN","value":["active","archived","completed"]},{"field":"ad.updated_time","operator":"GREATER_THAN","value":1582578140}]', 'summary': 'true', 'fields': 'updated_time,id'}

  Status:  400
  Response:
    {
      "error": {
        "type": "GraphMethodException",
        "message": "Unsupported get request. Object with ID 'act_4XXXXXXXXXXXX4' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
        "code": 100,
        "fbtrace_id": "AkC_QOl81J_K3geIwCnMSj9",
        "error_subcode": 33
      }
    }`

**Comment by mattredlon** [comment]
Is this something you should be aware of @luandy64?

**Comment by cfadams** [comment]
Same issue here - no changes had been made to the Stitch connector. Have tried reauthorizing and deleting and recreating the connection; same error.

**Comment by mattredlon** [comment]
Thanks for sharing the Facebook issue @luandy64 - hopefully we hear back soon. Clearly affecting a lot of people. I'll leave open here until we hear back.

**Comment by mattredlon** [comment]
This was resolved by Facebook. Thanks @luandy64 !
